language: node_js
node_js:
  - '7'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - babel server -d lib && node lib/migrations/tables

after_script:
  - npm run coverage

notifications:
  email: false
