version: '3'

services:
  app:
    container_name: banka
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://awezzylb:VNFSkCvg3AWlWddYlQnZzfhF1hYD6Lin@isilo.db.elephantsql.com:5432/awezzylb
      REDIS_URL: redis://redis:6379

  db:
    container_name: db
    image: postgres:11-alpine
    expose:
      - '5432'
    ports:
      - '5430:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: banka_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    command: ['npm', 'run', 'migrate']
  
  redis:
    container_name: redis
    image: redis
    ports:
      - '6378:6379'
