version: '3'

services:
  app:
    container_name: banka
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - banka-db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://awezzylb:VNFSkCvg3AWlWddYlQnZzfhF1hYD6Lin@isilo.db.elephantsql.com:5432/awezzylb
    command: >
       ash -c "npm run migrate && npm run serve"

  banka-db:
    container_name: banka-db
    image: postgres:11-alpine
    expose:
      - '5432'
    ports:
      - '5430:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: banka_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    command: ['npm', 'run', 'migrate']
  
  banka-redis:
    container_name: banka-redis
    image: redis
    expose:
      - '6379'
    ports:
      - '6378:6379'
    command: ["redis-server", "--bind", "redis", "--port", "6378"]
    hostname: redis
